[tools]
actionlint = "latest"
crane = "latest"
gitleaks = "8.22"
hadolint = "latest"
markdownlint-cli2 = "latest"
shellcheck = "latest"
snyk = "latest"
task = "3"
trivy = "latest"
yamllint = "latest"
