name: Maintenance

#
# Requires 'BOT_TOKEN' as Dependabot secret to push signed commits
#

on:
  workflow_dispatch:
    inputs:
      job:
        description: Job to run
        type: choice
        options:
          - Lint commit messages
          - Pin Actions and Docker images
        required: false
        default: Pin Actions and Docker images
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_commits:
    # Lint commit messages failing if they're not conventional
    name: Lint commit messages
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      github.event.forced == false && github.actor != 'dependabot[bot]' &&
      (github.event.inputs.job == 'Lint commit messages' ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request')
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # ratchet:wagoid/commitlint-github-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configFile: .github/.linters/commitlintrc.yaml

  pin_actions_and_docker_images:
    name: Pin Actions and Docker images
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      github.event.inputs.job == 'Pin Actions and Docker images' ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Check for workflow file changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # ratchet:dorny/paths-filter@v3
        with:
          filters: |
            workflows:
              - '.github/workflows/**'

      - name: Exit if no workflow changes
        if: steps.filter.outputs.workflows != 'true'
        run: echo "No changes in .github/workflows/, exiting..." && exit 78

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # ratchet:actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Ratchet
        run: go install github.com/sethvargo/ratchet@latest

      - name: Pin
        run: ratchet pin $(ls .github/workflows/*.{yaml,yml} 2>/dev/null)

      - name: Push changes
        env:
          COMMIT_MESSAGE: "ci: pin actions and Docker images in workflows [skip ci]"
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            gpg --import <(echo "${{ secrets.BOT_GPG_PRIVATE_KEY_BASE64 }}" | base64 -d)
            git config user.name "gha-bot"
            git config user.email "gha-bot.noreply.wdx1x@tenet.pm"
            git config user.signingkey "ABD02F54EDDADCB6"
            git config commit.gpgsign true
            git status --porcelain
            git commit -am "$COMMIT_MESSAGE"
            git push origin main
          else
            echo "No changes to commit."
          fi

  dependabot_automerger:
    name: Dependabot Automerger
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # ratchet:dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update branch and enable auto-merge
        if: contains('automerged-security,automerged-versions', steps.dependabot-metadata.outputs.dependency-group)
        run: |
          if gh pr view "$PR_URL" --json mergeStateStatus | grep -q "BEHIND"; then
            echo "Branch is behind base branch, updating..."
            gh pr update "$PR_URL" --update-branch
            sleep 10
          fi
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
